[package]
name = "img-prepend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.52", features = ["derive"] }
fatfs = "0.3.6"
fscommon = "0.1.1"
gpt = "4.1.0"
indicatif = "0.18.3"
uuid = "1.18.1"
